source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "18.04-LTS"
  location                          = "France Central"
  managed_image_name                = "myPackerImage"
  managed_image_resource_group_name = "myResourceGroup"
  os_type                           = "Linux"
  subscription_id                   = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  tenant_id                         = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  vm_size                           = "Standard_B2s"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]


  provisioner "file" {
      destination = "/tmp/authorized_keys"
      source      = "./keys"
  }

  provisioner "shell" {
  inline = [
    "sudo cp /tmp/authorized_keys /root/.ssh/authorized_keys","sudo apt update && sudo apt upgrade -y"
  ]
  }
  provisioner "ansible" {
    playbook_file = "./ansible/playbook.yml"
    ansible_ssh_extra_args = [
      "-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa"
   ]
  }
}